name = "CalcDist"
uuid = "0388be45-1932-4690-98b2-a3456dc81ac3"
authors = ["mindonly <thesanch@gmail.com>"]
version = "0.1.0"

[deps]
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
